### ISSUE TITLE
石を画像ファイルに変更する

### ISSUE THREAD

**Issue by closekn** [wakatakeru/infoexpr2-bustra#11]
## 概要
UIを改良する。
ブロックの形状を変更する。

## 目的
ゲームの見栄えのため。

## 提案内容
ブロックとして使用する、著作権フリーの画像を探してくる。

**Comment by wakatakeru** [comment]
### 探す画像の提案
具体的には、ブロックの画像とかを探してくると良さそう？
正方形の画像のほうが扱いやすいと思います。
いっそ作る？

**Comment by wakatakeru** [comment]
これは #8  の分割された内容です

**Comment by wakatakeru** [comment]
[ref: ](https://sozai.cman.jp/icon/operation/close/) @kohshow が見つけてきてくれました🎉
これ使って、いい感じにできそう？🤔

**Comment by wakatakeru** [comment]
## 提案内容

ルートディレクトリに`bin`ディレクトリを配置して、石の画像ファイル4つを`png`形式で配置する。

## タスク
- [x] ルートディレクトリに`bin`ディレクトリを作成する
- [x] 石の画像ファイルを生成する
- [x] 画像をディレクトリ内に配置する

**Comment by wakatakeru** [comment]
PR: #21

**Comment by wakatakeru** [comment]
#21 で解決されたので、closeします！
