### ISSUE TITLE
Scoreクラスの得点計算のルールを確定させる

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#19]
## 概要

Scoreクラスの得点計算のルールが微妙に定まっていない。
そのため、calcPointメソッドが実装できない。

## 目的

得点計算のルールを確定させて、calcPointメソッドの仕様を確定させる。
#12 のクローズを目指す。

## 提案内容

現在、@nd3 の提案では、
`消したブロックの数 * 連続で消えた連の数 / 2 * 100`
となっています。

## タスク
- [x] 得点計算の数式を確定する
- [x] calcPointメソッドを実装する

**Comment by nd3** [comment]
そもそも、なぜこんな数式かと言いますと、10点とか100点の刻みのほうがゲームっぽいかなあと思ったのと、「12345678」みたいなスコアになったとして、ちょっと見栄えが悪いかなあと思ったのでそうした次第です。
式中に「÷2」と「×100」が入ってしまってるので、「それ×50じゃん」と言われればそれまでなんですが…
なんか締まりが悪いので、意見を聞きたいです！

**Comment by wakatakeru** [comment]
100点刻み、とてもいいんじゃないと思います！👍
確かに100点刻みのほうがゲームっぽい感じはありますね。
`*50`では無く、`/ 2`と`* 100`は、どちらも入れておいたほうがいいと思います！
明示的に、`100点刻み`、コンボ回数は`/2`にするということがわかると思いますので！😘

**Comment by wakatakeru** [comment]
#23 で確定したので、クローズします！！！🎉
