### ISSUE TITLE
READMEの作成

### ISSUE THREAD

**Issue by closekn** [wakatakeru/infoexpr2-bustra#22]
## 概要
READMEが作成されていないため、ユーザにゲームを理解してもらうことができない。

## 目的
ゲームの起動方法・ゲームシステム・操作方法をユーザに理解してもらうため。

## タスク
- [x] 起動方法の確定
- [x] ゲームシステムの確定
- [x] 操作方法の確定
- [x] READMEの記述

**Comment by wakatakeru** [comment]
Runnable JAR化する手順も加えておいたほうがいいかもですね！

**Comment by closekn** [comment]
課題としてはRunnable JARファイルを提出するものとなっているのですが、Runnable JAR化する手順も記述したほうが良いでしょうか？

**Comment by wakatakeru** [comment]
そうですね！手順も記述しておくほうがいいと思います！
そうすれば、ソースコードを変更したあとでも、Runnable JAR化する手順が明確になってわかりやすいですしね！👍

**Comment by wakatakeru** [comment]
#29 で実装中…

**Comment by kohshow** [comment]
#29 で実装完了
