### ISSUE TITLE
Windows環境でブロックの画像にジャギーが出る

### ISSUE THREAD

**Issue by kohshow** [wakatakeru/infoexpr2-bustra#31]
## 概要
Windows環境でゲーム実行画面のブロックの画像にジャギーが発生している。

## 目的
OSを問わず、画像を滑らかに表示する。

## 提案内容
サイズの調整、画像形式の変更を行う。

## 備考
#30 で修正中

**Comment by wakatakeru** [comment]
#30 で解消されたためClose
