### ISSUE TITLE
メニュー画面群を実装する

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#32]
## 概要

メニュー画面を実装して、ゲームスタート/ゲームエンドで情報を提示したり、
情報を取得したりする。具体的に必要なメニュー画面は以下の通りである。

### スタートメニュー

- ゲーム名表示(画像 or テキスト)
- ユーザ名のテキストボックス
- 盤面の大きさのテキストボックス
- 「ゲームスタート」ボタン
### エンディングメニュー

- スコア表示(テキスト)
- なんか"おつかれさまでした"みたいな一言(テキスト)

## 目的

- 盤面の大きさが指定するため
- ユーザ名を指定するため
- スコアをユーザが確認する方法を確保するため

## 提案内容

- 画面のレイアウトができた時点でレビューを受ける

## タスク
- [ ] スタートメニューのレイアウトを作成する
- [ ] エンディングメニューのレイアウトを作成する
- [ ] スタートメニューで指定した値を取得できるゲッターを作成する
- [ ] エンディングメニューに表示する値を設定するセッターを作成する

**Comment by nd3** [comment]
#46 で解決されたので、閉じます！
