### ISSUE TITLE
ブロックの更新を時間を開けて行う

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#33]
## 概要

ブロックの更新を時間をおいて行う。
一挙にブロックが消えたり、追加されたりしないようにする。

## 目的

ユーザに何個ブロックが消えたかわかりにくいため。

## 提案内容

Boardクラスのメソッドを更新する。
Thread使う感じになりそう。

**Comment by nd3** [comment]
http://techtipshoge.blogspot.jp/2013/07/swingrepainttimer.html
ここによるとThread.sleepだとダメそうです。
実際にfor()ループ中のsleepがまとめてくる感じになっています

**Comment by nd3** [comment]
なんとか試行錯誤してみましたがぼくの力じゃうまくできなかったです💧
助けて💧

**Comment by nd3** [comment]
実現できそうにないので、クローズします(´；ω；｀)
