### ISSUE TITLE
本体処理を書き換える

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#35]
## 概要

本体処理を書き換えて、ゲームのメニュー表示、ゲーム自体の処理、Timerをそれぞれ
スレッドとして稼働させるようにする。
本体処理の名前は、`Main`クラスとする。
また、ゲーム自体の処理である`Baseクラス`は`Game`クラスに書き換える。

## 目的

Timerを有効にして、3分で割り込みを掛けられるようにするため。
更に、メニューの表示も本体処理で行うようにする。

## 提案内容

本体処理の名前を`Main`クラスとする。
`Main`クラスでは、各種Menu、Game、Timerをスレッドとして呼び出すようにする。

## タスク

- [ ] `Base`クラスを`Game`クラスに書き換え
- [ ] `Game`クラスを修正してゲームの実行に特化させる
- [ ] `Game`クラスの`player`変数をstaticにする
- [ ] `Main`クラスを作成する
- [ ] ` Timer`クラスによる割り込みを有効する
- [ ] メニューの表示に対応させる

**Comment by nd3** [comment]
#37 で解決されたので、閉じます！
