### ISSUE TITLE
スコアサーバのためのHTTPクライアントを実装する

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#39]
## 概要

bustraゲームは、時間内に、できるだけ多くのスコアを取得することを目的としている。
この特性上、スコアサーバを設置することで、多数のプレイヤとの競争が可能になる。
別プロジェクトとして、Ruby on Railsを用いた[スコアサーバ](https://github.com/wakatakeru/infoexpr2-bustra-score_server)を作成した。
これは、所定の内容をPOSTすることで、データベースへの登録を可能にしている。

ここで、実際にクライアントである本プロジェクトのゲームで取得した点数を
HTTPを用いて、サーバに送信するクライアントを実装する。

## 目的

bustraゲームは、時間内に、できるだけ多くのスコアを取得することを目的としている。
この特性上、スコアサーバを設置することで、多数のプレイヤとの競争が可能になる。

## 提案内容

[ref](http://www.atmarkit.co.jp/ait/articles/0407/27/news104.html) を参考にして実装する。

**Comment by nd3** [comment]
マージしたのでクローズします！
