### ISSUE TITLE
Runnable JAR 化したときに画像ファイルが読み込めない問題の解決

### ISSUE THREAD

**Issue by closekn** [wakatakeru/infoexpr2-bustra#55]
## 概要
今のコード中の画像ファイルへのパスの記述法であると、Runnable JAR 化したときに画像を読み込むことができない。課題ページに記述されている方法を試したが、コンパイルエラーとなった。

## 目的
jarファイルで実行した時に画像を表示させたい。

## 提案内容
ヘルプ

## タスク
- [x] 方法の探索
- [x] コードの修正

**Comment by closekn** [comment]
http://pineplanter.moo.jp/non-it-salaryman/2017/04/07/java-icon-in-jar/
このサイトで、どうして今のままではjarファイルで画像ができようされないかはわかりやすく悦明されています><

**Comment by closekn** [comment]
https://stackoverflow.com/questions/19388141/java-imageio-readgetclass-getresource-returns-null
このサイトを参考にすることで解決しました！

**Comment by kohshow** [comment]
#57 で解決しました！
