### ISSUE TITLE
Windows環境でjavacができない

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#6]
## 概要

ソースファイルのエンコードが、`UTF-8`であるため、
Windows OS だと、正しくコンパイルできない。

## 目的

OSを問わず、正しくコンパイルできるようにする

## 提案内容

コンパイルの手順書を変更し、コンパイルできるようにする。
特にREADME.mdを修正する。

**Comment by wakatakeru** [comment]
[ref](https://www.javadrive.jp/start/encoding/index2.html) を参考にする。

**Comment by closekn** [comment]
良さそう

**Comment by wakatakeru** [comment]
#7 で解決されたため、クローズします
