### ISSUE TITLE
ゲームの作成方針を決定する

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#8]
## 概要

ゲームの作成方針を決定する。これは、ゲームに何を実装すべきか明確にするためである。

## 目的

ゲームの作成方針が決定していないため、実装に移れない。
ゲームの判定ルールの策定や、UIの実装方向について検討する。

## その他

そのissueは、方針が決定し次第、分割します😘

**Comment by wakatakeru** [comment]
### 追加したい機能
1. 判定処理を追加する #1 
2. UIの改良
  ブロックの形状の変更をする
3. 音を付ける
4. 得点機能を追加する
5. 時間制限を設ける
  時間によって、得点に倍率を設定する

**Comment by wakatakeru** [comment]
時間制限、どうしましょう。1テイク、3分(180秒)とかでどうでしょ？

**Comment by closekn** [comment]
とりあえず3分で良さそう。完成後にプレイしてみて必要があれば変える感じで良さそう。

**Comment by wakatakeru** [comment]
作成終了したので、クローズします！おつかれさまでした！！！！！
