### ISSUE TITLE
ゲームの効果音を付ける

### ISSUE THREAD

**Issue by wakatakeru** [wakatakeru/infoexpr2-bustra#9]
## 概要

#8 に基づいてゲームに効果音を付ける。
例えば、ブロックの移動時にクリック音をつけるなどする。

## 目的

ゲームの操作をしやすくするため。

## 提案内容

著作権フリーの効果音を探してくる。
更に、移動時などに効果音を挿入する。

## タスク
- [ ] 音楽を探してくる
- [ ] ディレクトリに格納する
- [ ] ソースコードから呼び出す

**Comment by kohshow** [comment]
効果音の格納するディレクトリはbinになりますか？

**Comment by nd3** [comment]
時間的制約により、 #53 #54が実現不可能となったので、クローズします(T_T)
